import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Layout from "../components/Layout";
import Sheet from "../components/Sheet";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Planner</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Sheet title="Create an Event">
          <p className="mb-8">
            You can use Planner to plan events with your friends
          </p>
          <Link
            className="text-md hover:text-white-100 rounded-lg bg-blue-500 p-2 text-blue-100 hover:bg-blue-700"
            href={"/events/new"}
          >
            Plan an event
          </Link>
        </Sheet>
      </Layout>
    </>
  );
};

export default Home;
